### ISSUE TITLE
Libraries...

### ISSUE THREAD

**Issue by jcredland** [ODDSound/MTS-ESP#1]
Guys we've been looking at this.  It would be a lot easier if it was a static library.  And is the windows library built with /MD or /MT? We'd probably need both for different projects.  It would be even easier if it was just a bit of source we could bundle into our JUCE app and not worry about linking a library in at all :)

There's nothing more hassle than waiting for a library update when the build architecture changes or you've got an urgent bug fix!

**Comment by olicash** [comment]
Are you building a Master?  If not there should no concern here.  If you are adding Client support to a plugin just grab libMTSClient.h and libMTSClient.cpp from the Client folder and include them in your build.  That's it!  The master library is provided here for anyone wanting to build a Master, which they will need to add to their installer.

**Comment by jcredland** [comment]
Hey Oli!  Right, that's me diving in without reading the instructions properly.   I thought these would need to be added to the client, but I see what you are doing now!

Code first, ask questions later approach :)

**Comment by olicash** [comment]
Hey no worries!  Glad it makes sense.  Any other queries or anything lmk.
