### ISSUE TITLE
libMTS.so on linux mis-linked

### ISSUE THREAD

**Issue by baconpaul** [ODDSound/MTS-ESP#10]
Hi Folks!

`libMTS.so` from this repo on linux is mis-linked and is missing symbols from shm.

Specficially take this C++ program

```
#include <dlfcn.h>
#include <iostream>

int main()
{
auto h = dlopen( "/usr/local/lib/libMTS.so", RTLD_NOW);
std::cout << h << " " << dlerror() << std::endl;
}

```
results in

```
paul@paul-linux:~/mts$ g++ -std=c++17 x.cpp -ldl 
paul@paul-linux:~/mts$ ./a.out
0 /usr/local/lib/libMTS.so: undefined symbol: shm_open
```

if I modify my program so it is

```
#include <dlfcn.h>
#include <iostream>
#include <unistd.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <sys/stat.h>
int main()
{
shm_open("",0,0);
auto h = dlopen( "/usr/local/lib/libMTS.so", RTLD_NOW);
std::cout << h << " " << dlerror() << std::endl;
}
```

I get 

```
paul@paul-linux:~/mts$ g++ -std=c++17 x.cpp -ldl -lrt
paul@paul-linux:~/mts$ ./a.out
0x55c4c2734f10 
```

I'm seeing if I can do the same to clients but something else is also blowing me out. So

1. It's a bummer the client reports *no* errors! and
2. Your .so seems to be mis-linked and has unresolved symbols which aren't part of a standard plugin

Any thoughts welcome!?

**Comment by olicash** [comment]
Fixed, thanks for reporting!
