### ISSUE TITLE
typos in Client header comments: microtuing + connnected

### ISSUE THREAD

**Issue by sophiapoirier** [ODDSound/MTS-ESP#13]
There are a couple of typos in the comments in `Client/libMTSClient.h`:
microtuing -> microtuning
connnected -> connected

I tried to open a PR but:
```
ERROR: Permission to ODDSound/MTS-ESP.git denied to sophiapoirier.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```
I have attached the patch though.
[typo.patch](https://github.com/ODDSound/MTS-ESP/files/12207736/typo.patch)

**Comment by olicash** [comment]
Thanks again, have corrected.
