### ISSUE TITLE
libMTSClient will misinterpret some non-Universal SysEx

### ISSUE THREAD

**Issue by EvanBalster** [ODDSound/MTS-ESP#5]
This state in `parseMIDIData`  (line 169) will interpret any SysEx containing 7E or 7F followed by the sequence <any byte>, <08> <01-09> as a MIDI Tuning Standard message.  This could happen, for example, when receiving MIDI-CI messages or other manufacturer-specific SysEx messages, and might produce unexpected change in client tuning.

Additionally, the implementation conflates Device ID with SysEx ID.  Device ID is always one byte in length, with a value of 0x7F indicating that the message is broadcast to all receivers or channels.

As a sidenote, please consider participating in the MIDI Association where these standards and their supporting documentation are developed.  I'm in a subcommittee concerned with Pitch & Tuning.

**Comment by olicash** [comment]
Happy to fix, but do you or anyone on the subcommittee know, or would be interested in finding out why Scala is adding extra bytes to the start of MTS SysEx messages?  As you can see in the comment, that is the reason for adding that line.  For example at the start of a bulk format message exported from Scala (MTS 01, or synth 107 in Scala), looks like F0 83 17 7E 00 08...

Happy to participate, what's the process to get involved?  Feel free to send invite over to info@oddsound.com.

**Comment by EvanBalster** [comment]
A byte with value 0x83 cannot appear in a valid SysEx sequence (top bit must be zero for all data bytes).  The byte sequence you've written would therefore seem to indicate either a faulty implementation or something that isn't a system exclusive event (such as an SMF meta event).

I recommend reviewing the MIDI Tuning Standard specification, available here: https://www.midi.org/specifications/midi1-specifications/general-midi-specifications/general-midi-2/midi-tuning-updated
Basing one implementation on another can cause errors in implementation to carry over. Following the spec is the best way to secure interoperability with other MIDI products. It's particularly concerning in this case because your code is presented as a reference implementation. 

Information about joining the MIDI Association as a member company is available here: https://www.midi.org/about

**Comment by olicash** [comment]
Well, I believe it is now fixed and compliant, hopefully concern alleviated.  Please let me know if you spot any other errors though.
