### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by pauldavisthefirst** [ODDSound/MTS-ESP#6]
It's very nice that you mention the location for the library on Linux. But there seems to be neither source code for the library, nor a Linux build of the library. There's also no Linux version of the basic client. This prevents us using this in the context of the plugins we maintain for Ardour/Mixbus, which is a shame, and discourages any use of this by other Linux-based plugin developers.

**Comment by lewiji** [comment]
+1. One of the devs said on fb he's working on it, but doesn't currently have a Linux box set up. If that's still the case I wouldn't mind having a go at producing a build, if it were allowed (proprietary sources etc...)

**Comment by benthevining** [comment]
+1. I'm working on developing a new plugin, and I would really, really love to be able to integrate MTS-ESP, but I am quiet weary of anything that won't work across every platform & architecture I need to target. If Linux support is added, I will absolutely be using MTS-ESP in all my future projects...

**Comment by benthevining** [comment]
I don’t have a Linux machine myself, so I can’t test it, but my GitHub actions build of a plug-in incorporating the MTS Client seems to have succeeded on Linux...

**Comment by olicash** [comment]
Hi, apologies for this.  It was not our intention to leave it too long before uploading a Linux build of the library.  We now have a Linux machine set up and can do one.  We have also implemented IPC support which has been working fine in alpha testing.  I'm moving this to beta testing and, if all is well, will upload a Linux version with IPC support, as it seems sensible to get both things done in one go.  With IPC in we can do an iOS build too!

**Comment by olicash** [comment]
Many hosts can now run optionally plug-ins in separate processes e.g. Bitwig, Waveform, FLStudio and Reaper.  IPC support allows MTS-ESP to work if a user has this configured.  It's especially necessary in FLStudio on Windows, where plug-ins must be run 'bridged' for DPI scaling, and also in Logic on an ARM Mac, where native ARM and Intel plug-ins run in two separate process.  That said, MTS-ESP IPC support will have the option to be disabled via a config file, should it be necessary.

**Comment by pauldavisthefirst** [comment]
Ah yes, that stuff. We don't do this in Ardour (and never will, since it cannot scale). But I see why it's necessary. Thanks for the clarification.

**Comment by benthevining** [comment]
IPC will be a great feature to have too! Thank you for your work on this!

**Comment by olicash** [comment]
x86_64 Linux build of libMTS now added.  If different architecture required do let us know.  Thanks!

**Comment by pauldavisthefirst** [comment]
so is the plan for libMTS to remain binary only/closed source?

**Comment by olicash** [comment]
That is the current plan, for compatibility and to keep the integration requirements as low as possible.  If you have any queries, suggestions or requests feel free to drop us a message - tech@oddsound.com.
