### ISSUE TITLE
MTS-ESP generates abundant compiler warnings

### ISSUE THREAD

**Issue by zardini123** [ODDSound/MTS-ESP#8]
I recently discovered MTS-ESP trips a spew of warnings provided by Apple (macOS) g++ and g++-11 from GNU gcc.  I discovered this when including MTS-ESP in a JUCE project with the recommended warning flags included in CMake build.  From what I understand the recommended warnings flags from JUCE includes `-Wconversion`.  Using `-Wconversion` alone with Apple gcc returns 18 warnings with MTS-ESP Client only.

Afterward, I discovered some other silly warnings when manually compiling with `-Wall`.  A short snippet follows:
```
libMTSClient.cpp:183:13: error: variable 'bank' set but not used [-Werror=unused-but-set-variable]
  183 |         int bank=-1,prog=0,checksum=0,deviceID=0;short int channelBitmap=0;   // maybe we'll want to use these at some point
```

Apple g++ and GNU gcc provides radically different `-Wconversion` warnings.  From my experience, the Windows flag that has similar `-Wconversion` output is `/W4`.  I've not tried MTS-ESP using Windows suite of warnings, but I'd imagine it'd be similar.

For the project I'm using MTS-ESP in I'm using the excessive setup of `-Wall -Werror -Wextra`, which makes using MTS-ESP hard to use.

I'd say it'd be rather important to mitigate these warnings as some whom included the library may find these warnings as fatal (i.e. using `-Werror`).

To automate the catching of these errors in the future, I'd highly recommend setting up a CLI (possibly Travis CLI?) to compile on all three platforms with the warning elevations attached.

I'm very curious to hear what you think!

**Comment by olicash** [comment]
Thanks for the detailed report.  I have just pushed a commit which silences all -Wconversion warnings I could see here.  Some of the others -Wall throws up I think I'm going to leave for now, for example the -Werror=unused-but-set-variable one above.  Someone might want to use that function elsewhere for parsing MTS SysEx data and require the data parsed into those variables.  Try with the the version from the latest commit and if you still see any warnings you feel it's important to silence do let me know.  Cheers, Oli.

**Comment by zardini123** [comment]
> I have just pushed a commit which silences all -Wconversion warnings I could see here.

Yep!  Works great!  Master seems great too!

> Someone might want to use that function elsewhere for parsing MTS SysEx data and require the data parsed into those variables.

How would someone access those variables if they are stuck inside the scope of the function?  Could this instead be accomplished with a structure output?  For example:
```
struct sMTSExtraInfo {
  int bank,
  int prog,
  int checksum,
  int deviceID,
  short int channelBitmap,
};
```
and then output via using a C "pass by reference"
```
inline void parseMIDIData(const unsigned char *buffer, int len, sMTSExtraInfo *extraInfoOut) {...}
```

If the `inline void parseMIDIData(const unsigned char *buffer, int len)` overload then called the overload mentioned above with a dummy instance of the extraInfoOut, no code would have to be changed much.  If the dummy instance still trips the unused but set, one can suppress any of those warnings by simply casting to void:
```
(void)extraInfoOut;
```

If you do not want to give the user the structure, you can still suppress the warning with the void thing mentioned above.

Thank you very much, and I'm curious to hear what you think!

**Comment by olicash** [comment]
Indeed as you suggest, a struct would work, but that is left up to the developer.  I wasn't really talking about it being used in the context of the MTS-ESP library, more as a reference MTS SysEx parser, to lift out and use as a starting point for adding MTS SysEx support to other programs or devices.  In fact I haven't uploaded it yet but just the other day I created a little pure C lib which does just that, which could be used e.g. for adding MTS SysEx support to the firmware of a hardware device.

**Comment by olicash** [comment]
I've commented out the unused vars to silence the compiler warnings, I think that's the best thing to do for now!

**Comment by zardini123** [comment]
> I wasn't really talking about it being used in the context of the MTS-ESP library, more as a reference MTS SysEx parser, to lift out and use as a starting point for adding MTS SysEx support to other programs or devices.

Ahhh that makes sense!  

> In fact I haven't uploaded it yet but just the other day I created a little pure C lib which does just that, which could be used e.g. for adding MTS SysEx support to the firmware of a hardware device.

I'd be excited to see that library once its released!

> I've commented out the unused vars to silence the compiler warnings, I think that's the best thing to do for now!

You can suppress the warnings by casting each variable to void if you don't want your code sitting with code comments.  Its a no-op in resulting compilation, I believe, and also as you may think it "uses" the variable.  If you think comments is best, then that works too!

I'll give the master a pull and I'll give it a go!

**Comment by zardini123** [comment]
It compiled great, but only one warning left.  Seems like the `realtime=false` variable was missed in your last commit.  Once that's commented it should be perfect!  Thank you!

**Comment by olicash** [comment]
Oops, forgot that one, done now.  Thanks!
